safe: true
timezone: Europe/Stockholm
markdown: kramdown

exclude: [
    '.jshintrc',
    'CNAME',
    'css',
    'Gemfile',
    'Gemfile.lock',
    'Guardfile',
    'psd',
    'README.md',
    'vendor'
]

sass:
    style: compressed

title: Förbannad statistik
description: En samling intressanta samhällsfenomen i form av statistik som annars kanske är svårtillgänglig för de flesta.
live_url: https://forbannadstatistik.polyscopic.works
live_hostname: forbannadstatistik.polyscopic.works
email: markus@polyscopic.works
live_rss_url: https://forbannadstatistik.polyscopic.works/feed.xml
google_analytics_id: UA-43257918-1
